# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lanbig
email: lanbig@msn.com
description: In the world of Data Science and Machine Leaning. 
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://lanbigben.github.io' # the base hostname & protocol for your site
twitter_username: 
github_username: lanbig
linkedin_username: lanbig

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging

# Pagination
paginate: 12

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  ben:
    name: Ben
    display_name: Ben Rodrawangpai
    bio: Ben has over 3 years of experience in Data Science, and he is a MSc in Predictive Analytics candidate at DePaul University. Also, he is working as a Data Analytics Intern at Underwriters Laboratories Inc.
    gravatar: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAATOAAAAJGU3ZGE5YjZkLWYyNWEtNDUyMi04OWI5LTY4N2E5ODNkYTgxMg.jpg
    email: lanbig@msn.com
    web: 
    linkedin: lanbig
    github: lanbig
